### ISSUE TITLE
CT On-boot (not working) & Un/Suspend/Terminate (not working)

### ISSUE THREAD

**Issue by habibulilalbaab** [The-Network-Crew/Proxmox-VE-for-WHMCS#34] opened 2023-07-20 13:44 UTC
LXC Plan Set On-boot CT checked, but after create not set to enable start on boot

**Comment by habibulilalbaab** [comment] 2023-07-20 13:53
suspend, unsuspend, and terminate not work in my environment PVE 7.4-16

**Comment by lsthompson** [comment] 2023-09-13 03:28
LXC/CT on-boot now fixed (ready for v1.2.2)

As for Suspend/Unsuspend/Terminate not working, can you share error details etc please?

**Comment by lsthompson** [comment] 2023-09-13 05:47
@habibulilalbaab we've had confirmation that suspending and unsuspending seems to work for VMs at least in v1.2.1

We will close this shortly if no more info, as we've resolved the other part. Thanks for your requests.

**Comment by jbrouhard98** [comment] 2023-09-14 03:50
Okay Correction.   I do not see any indication that suspending or terminating a VM is doing anything via PVE from WHMCS.   I do not know what these functions are intended for exactly?

**Comment by lsthompson** [comment] 2023-09-14 04:16
Intended for automatic handling of non-payment. Abuse cases. etc.

Interesting. Will dig into this. I suspect the errors aren't being passed back.

**Comment by jbrouhard98** [comment] 2023-09-14 04:22
Honestly, I think a good approach to this would be on Suspension, Stop the VM manually and lock it. from being started by the client using PHP wizardry.

Unsuspend, you can remove that lock and let the client start it themselves.   Terminate, i would say delete the VM/container ?

**Comment by lsthompson** [comment] 2023-09-14 05:05
Is it possible to lock manually, or is that just for failed PVE events?
Seems there is no /status/lock per the API Viewer.

Stop/Start now in the repo to check?
If no joy, anything in (any) PVE?

**Comment by jbrouhard98** [comment] 2023-09-14 05:08
there's no way to lock it directly via PVE.   However you can lock out the ability of the end user to do much of anything with their service/product through WHMCS itself perhaps.

I'll update the repo in the morning.. i'm actually about to pass out.

**Comment by lsthompson** [comment] 2023-09-14 05:13
Yeah but if the PVE side works now, then WHMCS will change status to suspended, and that SHOULD mean that Client Area access goes dark.

However if you can still boot once suspended (stopped) that's a problem. 

Similarly if it doesn't stop the VM at all but marks suspended in WHMCS.

Please let me know how you get on so we can keep improving it!

**Comment by lsthompson** [comment] 2023-09-14 22:56
@jbrouhard98 - this is the final item now before we're looking to push v1.2.2 out :-)

https://github.com/The-Network-Crew/Proxmox-VE-for-WHMCS/milestones

**Comment by lsthompson** [comment] 2023-09-14 23:05
I've just confirmed that a suspended service cannot see VM/CT info/graphs/etc, nor use the module buttons even if you find the slug from the source and try to run it manually.

`"Action Failed Product must be active to perform this action"`

**Comment by lsthompson** [comment] 2023-09-14 23:06
I've just tested suspending/unsuspending from the Admin Area, and they now work as expected. :-)

**Closed by lsthompson** 2023-09-14 23:06 UTC
Labels: bug
