### ISSUE TITLE
Getting a lock file error when cloning the vm template

### ISSUE THREAD

**Issue by leoskinnertm** [The-Network-Crew/Proxmox-VE-for-WHMCS#83] opened 2024-08-24 01:56 UTC
This is the error i get when i buy the vm package its all setup like it says in the readme and this is the module log i have

`PVE2 API: This API Request Failed.
HTTP CODE: 500,
HTTP ERROR: HTTP/1.1 500 can't lock file '/var/lock/qemu-server/lock-203.conf' - got timeout,
REPLY INFO: {"data":null}`

**Comment by leoskinnertm** [comment] 2024-08-24 16:20
i also followed the readme step by step so im not sure what the issue it

**Comment by MFHaZe** [comment] 2024-08-26 18:05
i am also facing the same issue but cant find any information on how to resolve it could be a common issue maybe?

**Comment by lsthompson** [comment] 2024-08-27 00:17
I am curious whether this may relate to #32 being implemented. 

If you enable logging in Module & in WHMCS, do you have any more logging either side of this failure?

**Comment by leoskinnertm** [comment] 2024-08-27 00:22
no its only that one error after i buy the package with it all setup if its a large vm template like over 10gb it will give this error but when testing with a 1gb vm template it works

**Comment by lsthompson** [comment] 2024-08-27 00:25
Thanks for the additional info - that would make sense given the error is ultimately just a timeout on getting lock.

How long does it take until it fails and logs that error? 30 seconds?

**Comment by leoskinnertm** [comment] 2024-08-27 00:27
yeah around 30 seconds

**Comment by leoskinnertm** [comment] 2024-08-29 02:51
any progress on a fix?

**Comment by leoskinnertm** [comment] 2024-08-29 03:33
1. template is stopped
2. yes
3. no tried a non template and still same issue
as for the potential fixes i don't currently have access to be able to run the commands and will get back to you once i do.

**Comment by leoskinnertm** [comment] 2024-08-31 01:17
@lsthompson finally got round to doing this should be in a good format to read let me know if there is anything else you need me to do.

command: qm unlock
output: none

command: pveversion -v
output: ```proxmox-ve: 8.2.0 (running kernel: 6.8.4-2-pve)
pve-manager: 8.2.2 (running version: 8.2.2/9355359cd7afbae4)
proxmox-kernel-helper: 8.1.0
proxmox-kernel-6.8: 6.8.4-2
proxmox-kernel-6.8.4-2-pve-signed: 6.8.4-2
ceph-fuse: 17.2.7-pve3
corosync: 3.1.7-pve3
criu: 3.17.1-2
glusterfs-client: 10.3-5
ifupdown2: 3.2.0-1+pmx8
ksm-control-daemon: 1.5-1
libjs-extjs: 7.0.0-4
libknet1: 1.28-pve1
libproxmox-acme-perl: 1.5.0
libproxmox-backup-qemu0: 1.4.1
libproxmox-rs-perl: 0.3.3
libpve-access-control: 8.1.4
libpve-apiclient-perl: 3.3.2
libpve-cluster-api-perl: 8.0.6
libpve-cluster-perl: 8.0.6
libpve-common-perl: 8.2.1
libpve-guest-common-perl: 5.1.1
libpve-http-server-perl: 5.1.0
libpve-network-perl: 0.9.8
libpve-rs-perl: 0.8.8
libpve-storage-perl: 8.2.1
libspice-server1: 0.15.1-1
lvm2: 2.03.16-2
lxc-pve: 6.0.0-1
lxcfs: 6.0.0-pve2
novnc-pve: 1.4.0-3
proxmox-backup-client: 3.2.0-1
proxmox-backup-file-restore: 3.2.0-1
proxmox-kernel-helper: 8.1.0
proxmox-mail-forward: 0.2.3
proxmox-mini-journalreader: 1.4.0
proxmox-offline-mirror-helper: 0.6.6
proxmox-widget-toolkit: 4.2.1
pve-cluster: 8.0.6
pve-container: 5.0.10
pve-docs: 8.2.1
pve-edk2-firmware: 4.2023.08-4
pve-esxi-import-tools: 0.7.0
pve-firewall: 5.0.5
pve-firmware: 3.11-1
pve-ha-manager: 4.0.4
pve-i18n: 3.2.2
pve-qemu-kvm: 8.1.5-5
pve-xtermjs: 5.3.0-3
qemu-server: 8.2.1
smartmontools: 7.3-pve1
spiceterm: 3.3.0
swtpm: 0.8.0+pve1
vncterm: 1.8.0
zfsutils-linux: 2.2.3-pve2```

command: qm config
output: ```bios: ovmf
boot: order=scsi0;ide2;net0
cores: 1
cpu: max
ide2: local:iso/Windows_Server_2022.iso,media=cdrom,size=4925874K
machine: pc-q35-8.1
memory: 1024
meta: creation-qemu=8.1.5,ctime=1724461530
name: Tester
net0: e1000=BC:24:11:6C:EB:50,bridge=vmbr0,firewall=1
numa: 0
ostype: win11
scsi0: local-lvm:base-106-disk-0,iothread=1,size=15G
scsihw: virtio-scsi-single
smbios1: uuid=5eefe5b4-70f7-420a-9da6-5e886b56bd1b
sockets: 1
template: 1
vmgenid: e51c281b-879d-4d18-bf48-469fbcf0b7b9```

command: cat /etc/hosts
output: default

command: hostname
output: correct hostname used to access proxmox panel

**Comment by lsthompson** [comment] 2024-09-04 02:28
Hi, can you please send the outputs without truncating/omitting/editing?

ie. `qm unlock templateID` & `qm config templateID`

If you're certain re: hosts and hostname being fine, it's OK to omit those.

**Comment by leoskinnertm** [comment] 2024-09-05 11:56
here is an image of the output let me know if you need anything else
![image](https://github.com/user-attachments/assets/d0459fa2-e81f-46b3-8900-60d5106f3819)

**Comment by lsthompson** [comment] 2024-09-05 23:10
Thanks for that. 

- Please remove the ISO from the template. 
- Also, please perform system updates to the PVE Host (you're running April 2024 kernel) then reboot.

Then try again and let us know.

**Comment by leoskinnertm** [comment] 2024-09-06 13:34
i have removed the iso but im a little confused on what you mean by perform system updates to the PVE Host i am running 8.2.2 and that is currently the latest version

**Comment by lsthompson** [comment] 2024-09-06 14:45
Your booted kernel version is old - can you please do a Proxmox system update and reboot the node?

That'll boot it into the latest kernel.

**Comment by leoskinnertm** [comment] 2024-09-06 15:18
could you provide a link that will help me update and understand what you mean because i have ran apt update and apt dist-upgrade and i can't update proxmox anymore since im on the latest 8.2.2 that came out august 22 of this year

**Comment by lsthompson** [comment] 2024-09-06 15:20
When did you last reboot Proxmox?

When you SSH in, the date at the top is the kernel build date. If it still says early 2024 then you need to reboot up to August 2024 kernel etc.

**Comment by leoskinnertm** [comment] 2024-09-06 15:22
i did the reboot command like an hour go and still says the same thing

**Comment by lsthompson** [comment] 2024-09-06 15:23
Screenshot of a new SSH prompt on the Proxmox host?

**Comment by leoskinnertm** [comment] 2024-09-06 15:26
![image](https://github.com/user-attachments/assets/7c71064d-e3f6-4a65-9e11-ff239c74660c)

**Comment by lsthompson** [comment] 2024-09-06 15:33
Outputs of below commands?

`uptime`

`uname -a`

**Comment by leoskinnertm** [comment] 2024-09-06 15:37
first command
![image](https://github.com/user-attachments/assets/938b2d75-7f68-4ee3-b65d-69355ff1b48c)

second command
![image](https://github.com/user-attachments/assets/b12743a1-5f15-4e69-b49d-e46aa3d048c9)

**Comment by lsthompson** [comment] 2024-09-06 22:32
Have you pinned your kernel version? It shouldn't be staying at `6.8.4-2` - latest is `proxmox-kernel-6.8.12-1` per repo.

Can you please share the results of `pvereport` on the PVE Node? I'd like to ensure that you're up-to-date. Thanks!

**Comment by leoskinnertm** [comment] 2024-09-07 11:07
here is a text version if you want a image version then i can send that but this is a unedited version of the output
[pvereport.txt](https://github.com/user-attachments/files/16917770/pvereport.txt)

**Comment by lsthompson** [comment] 2024-09-07 11:10
You seem to have broken repository config. No license for Proxmox, but Enterprise repositories enabled.

Using the GUI, disable Enterprise for Proxmox and Ceph, then add no-subscription for Proxmox.

Then go to Updates and refresh, then install all upgrades and reboot the node. Then try.

If no joy, re-send the `pvereport` again with all of the above done please & thanks!

**Comment by leoskinnertm** [comment] 2024-09-07 11:38
it is now up to date is there anything else i need to do
![image](https://github.com/user-attachments/assets/d5211d36-2415-491d-a707-d9ad2aec854e)
[pvereport.txt](https://github.com/user-attachments/files/16917899/pvereport.txt)

**Comment by lsthompson** [comment] 2024-09-07 11:45
Are you still facing the problem?

**Comment by leoskinnertm** [comment] 2024-09-07 12:07
done everything you said and its still timing out when cloning
![image](https://github.com/user-attachments/assets/9abcf0fc-5d56-4d3d-a8f8-674b8597349e)

**Comment by lsthompson** [comment] 2024-09-08 08:29
If you turn on Debug Mode in the module, and the Module Debug Log in WHMCS, then try again, what is logged?

**Comment by leoskinnertm** [comment] 2024-09-08 12:33
nope just that

**Comment by leoskinnertm** [comment] 2024-09-14 16:07
@lsthompson anything else i need to do or is this a module issue?

**Comment by lsthompson** [comment] 2024-09-14 22:25
Can you please share the below from before and after you try via WHMCS?

`journalctl -f`

Do you get the same problem via Proxmox itself, if you try to Power Off the same guest?

**Comment by leoskinnertm** [comment] 2024-09-17 13:56
@lsthompson sorry for the late reply been really busy let me know if there is anything else you need me to do

![image](https://github.com/user-attachments/assets/9d2dc792-08a2-41e5-b75d-eaf2494700f1)

![image](https://github.com/user-attachments/assets/9b9a3412-fbf3-4cb7-8dd1-564480be5b12)

**Comment by interuseration-IURT** [comment] 2024-09-21 10:34
The fact is that the module wait time is not long enough, resulting in the order being stuck in pending even though the virtual machine is successfully created.

**Comment by lsthompson** [comment] 2024-09-21 23:42
@kernelexception nice username! You've gone for a license, not owned - but glad it's working well. :-)

@interuseration-IURT it's a bit more complex than that, as it's not PHP killing it - rather it is PVE API.

@leoskinnertm thanks for your patience all - please check the updated **server** file (UNTESTED) now?

It is in repo main, but not released - you can view the changes (open to feedback): https://github.com/The-Network-Crew/Proxmox-VE-for-WHMCS/commit/b5f15514dbea2ec29bb591acb91c2d1c7e0f68cc [(file link)](https://github.com/The-Network-Crew/Proxmox-VE-for-WHMCS/blob/master/modules/servers/pvewhmcs/pvewhmcs.php)

**Comment by leoskinnertm** [comment] 2024-09-21 23:47
Replacing the server file this is now the new error i get
![image](https://github.com/user-attachments/assets/27bb5447-8382-4d71-903b-4ee193fbf8ea)

**Comment by lsthompson** [comment] 2024-09-21 23:51
Thanks for that. I think we're grabbing the UPID in the wrong way. Can you copy paste error here, and also confirm if the creation worked okay on PVE?

**Comment by leoskinnertm** [comment] 2024-09-21 23:52
Module Command Error
Proxmox Error: Failed to initiate clone. Response: "UPID:proxmox:001A6703:038A12C8:66EF5AD4:qmclone:110:root@pam:"

**Comment by lsthompson** [comment] 2024-09-22 00:05
OK thanks - please try the new version?

**Comment by leoskinnertm** [comment] 2024-09-22 00:10
like before it does start the cloning but i get this error

PVE2 API: This API Request Failed. HTTP CODE: 400, HTTP ERROR: HTTP/1.1 400 Parameter verification failed., REPLY INFO: {"errors":{"upid":"unable to parse worker upid"},"data":null}

**Comment by lsthompson** [comment] 2024-09-22 00:13
Yeah I was just reading up more on it - please try now. 

I suspect it will start, though may not fully handle OK. Let's see how you get on. :-)

**Comment by leoskinnertm** [comment] 2024-09-22 00:15
again, clone starts but throws this error:

Proxmox Error: Task failed with status: {"user":"root@pam","id":"110","node":"proxmox","status":"running","pstart":59551206,"pid":1735261,"type":"qmclone","upid":"UPID:proxmox:001A7A5D:038CADE6:66EF6180:qmclone:110:root@pam:","starttime":1726964096}

**Comment by lsthompson** [comment] 2024-09-22 00:23
Okay thanks for the update - try now. I've refined how it checks the task.

**Comment by leoskinnertm** [comment] 2024-09-22 00:28
seems to have the same issue

**Comment by lsthompson** [comment] 2024-09-22 00:31
Okay thanks, how about now?

**Comment by leoskinnertm** [comment] 2024-09-22 00:38
Seems to be working now but its not increasing the disk space once its done but the cpu and ram did change
![image](https://github.com/user-attachments/assets/5e964492-fec7-43b4-9060-905b84a7fe58)

**Comment by lsthompson** [comment] 2024-09-22 00:42
For disk, it'll need to know existing size and desired size. Also not fully automated as we can expand PVE Disk, but that won't expand PV/LV/partitions/etc.

**Comment by lsthompson** [comment] 2024-09-22 00:47
As for the issue at hand with file lock, are you happy it's solved?

If all seems well, I'll deploy v1.2.6 with it only, and work through the next 2 features by the end of the year.

**Comment by interuseration-IURT** [comment] 2024-09-22 00:59
I was happy to see that it seemed to work, but when I replaced the existing file it gave me a new error: Error: PVE2 API: Hostname/Username/Realm/Password/Port required for PVE2_API object constructor. I checked the server connection and it was fine.

**Comment by lsthompson** [comment] 2024-09-22 01:01
@interuseration-IURT thanks for the test & report - which type (QEMU/LXC) and method (create-new/clone-template)?

Please confirm which file you replaced? And how you're doing this - ie. Module Queue or Service Create button etc?

**Comment by interuseration-IURT** [comment] 2024-09-22 01:05
I just replaced the original module file with the file in the repository. The problem occurred when I executed clone-template. I used QEMU

**Comment by lsthompson** [comment] 2024-09-22 01:08
1. Okay, so the `/servers/pvewhmcs/pvewhmcs.php` file? (right)
Not the `/addons/pvewhmcs/pvewhmcs.php` file? (wrong)

2. Even though Server Config OK, please save & test again.

3. Does the module otherwise work before the file change?
ie. Have you followed **entire** README.md?

**Comment by interuseration-IURT** [comment] 2024-09-22 01:11
1.I have changed the files in both /addons/ and /servers/.
3.Yes . Before using this version, the module can work normally and clone-template, but it will cause the problem of this issue
2. I am trying again to avoid my own negligence

**Comment by lsthompson** [comment] 2024-09-22 01:13
1. OK, so long as you didn't put the /servers/ file in both folders. That won't work. Just check they are different?

2. Thanks for confirming.

3. Sounds good, thanks.

**Comment by interuseration-IURT** [comment] 2024-09-22 01:19
emm , I have used the new files in the repository and correctly replaced the old files

**Comment by interuseration-IURT** [comment] 2024-09-22 01:20
I checked again and confirmed that the problem was unlikely to be with me.

**Comment by lsthompson** [comment] 2024-09-22 01:22
OK, so save the Server Config (Proxmox root login in WHMCS Settings) again.

Then go to Module Config, and enable Debug Logging.
Also enable Module Debug Logging in WHMCS too.

From there, try the process again and copy the debug log entries into here please.

**Comment by interuseration-IURT** [comment] 2024-09-22 01:29
This problem has been solved. In fact, changing the module file requires reconfiguration in the product.

**Comment by interuseration-IURT** [comment] 2024-09-22 01:29
But I am sure I have encountered a new problem. My PVE is a cluster with node A and node B. The template is on node A, but it reads the template of node B, so it reports the error 500 unable to find configuration file for VM 201 on node 'node1'. When I migrate the template to node A, it reports unable to find configuration file for VM 201 on node 'node2'.

**Comment by lsthompson** [comment] 2024-09-22 01:31
Glad to hear that the issue is solved. We will deploy v1.2.6 today now there are 2 working installations.

As for the missing config file issue, are you able to share debug logging info once you've enabled it (in the 2 places)?

**Comment by interuseration-IURT** [comment] 2024-09-22 01:37
In fact, there is nothing in the module log. I only saw this in the system log:
![捕获](https://github.com/user-attachments/assets/872b9273-3f46-4755-a96f-c35347b07d8f)

This is my pve structure：
![image](https://github.com/user-attachments/assets/1d1a2187-aba6-412c-8405-f697ee8405f1)

**Comment by lsthompson** [comment] 2024-09-22 01:39
At the moment, I think you would want the Template on node1. 

Does your PVE log show WHMCS as connecting to node1 or node2?

For the Module Debug Log, you need to enable it in 2 different places - yes?

**Comment by interuseration-IURT** [comment] 2024-09-22 01:43
I have  enable it in 2 different places , but there is nothing
 
This is my pve logs
![image](https://github.com/user-attachments/assets/7b856757-5035-4f75-8e81-62187478a9bc)

The strange thing is that this problem sometimes occurs and sometimes does not. For example, just now I migrated to node1 again and it cloned successfully.

**Comment by lsthompson** [comment] 2024-09-22 01:46
OK, closing this issue as completed. Thanks everyone! :-)

If you can reliably reproduce that other problem, then please add some info to existing Issue #16 which may relate.

**Closed by lsthompson** 2024-09-22 01:46 UTC
Labels: bug-splat, please-test
