### ISSUE TITLE
Import VM

### ISSUE THREAD

**Issue by Juju100801** [The-Network-Crew/Proxmox-VE-for-WHMCS#86] opened 2024-09-25 23:02 UTC
Hello,

I already had VMs on my proxmox, I would like to know how to manually import them into the module so that customers can manage their servers?

Best Regards,
Juju

**Comment by lsthompson** [comment] 2024-09-25 23:04
Closing as duplicate of #75

**Closed by lsthompson** 2024-09-25 23:04 UTC
